### ISSUE TITLE
生成mysql 注释的dll能分先一下么?

### ISSUE THREAD

**Issue by psgogogo** [HelloSetsuna/Mybatis-Template-CodeSmith#1]
SchemaExplorer.MySQLSchemaProvider.dll 这个文件

**Comment by HelloSetsuna** [comment]
[SchemaExplorer.MySQLSchemaProvider.zip](https://github.com/HelloSetsuna/Mybatis-Template-CodeSmith/files/2775504/SchemaExplorer.MySQLSchemaProvider.zip)
试下看能不能用,我很久前配置的了

**Comment by psgogogo** [comment]
谢谢啊,已经找到可以用的了~!




| |
zhang xisheng
|
|
psgogogo@163.com
|
签名由网易邮箱大师定制
在2019年1月19日 20:13，Setsuna<notifications@github.com> 写道：

SchemaExplorer.MySQLSchemaProvider.zip
试下看能不能用,我很久前配置的了
